name: environment_plus
description: "A Flutter plugin that provides comprehensive device, app, and environment information for Flutter apps."
version: 1.0.0
homepage: https://github.com/neokn/environment_plus

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  device_info_plus: ^11.4.0
  package_info_plus: ^8.3.0
  slugid: ^1.1.2
  logging: ^1.3.0
  android_id: ^0.4.0
  manifest_info_reader: ^1.0.0
  connectivity_plus: ^6.1.4
  geolocator: ^14.0.0
  battery_plus: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
