name: Publish to pub.dev

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*.*.*'

jobs:
  publish-dry-run:
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: format
        run: dart format --set-exit-if-changed .
      - name: build_runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Publish to pub.dev (Dry Run)
        uses: k-paxian/dart-package-publisher@v.1.6.2
        with:
          credentialJson: ${{ secrets.PUB_CREDENTIALS_JSON }}
          skipTests: false
          dryRunOnly: true
          suppressBuildRunner: true

  publish-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: format
        run: dart format --set-exit-if-changed .
      - name: build_runner
        run: dart run build_runner build --delete-conflicting-outputs
      - name: build_runner
        run: dart run build_runner build --delete-conflicting-outputs
      - name: dry-run
        run: flutter pub publish --dry-run
        