name: Publish to pub.dev

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*.*.*'

jobs:
  publish-dry-run:
    if: startsWith(github.ref, 'refs/heads/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish to pub.dev (Dry Run)
        uses: k-paxian/dart-package-publisher@v.1.6.2
        with:
          credentialJson: ${{ secrets.PUB_CREDENTIALS_JSON }}
          skipTests: false
          dryRunOnly: true
          suppressBuildRunner: true

  publish-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish to pub.dev
        uses: k-paxian/dart-package-publisher@v.1.6.2
        with:
          credentialJson: ${{ secrets.PUB_CREDENTIALS_JSON }}
          skipTests: false
          dryRunOnly: false
          suppressBuildRunner: true
